### ISSUE TITLE
方法不存在

### ISSUE THREAD

**Issue by JimChenWYU** [telanflow/laravel-binlog#1]
类 FieldDTOCollection 继承 `Illuminate\Support\Collection`
在 makeFromArray 方法里调用 add 方法，可是 add 本来就不存在 Collection,
查了 laravel 好几个版本的文档也没发现Collection有提供这个方法，只有push

**Comment by JimChenWYU** [comment]
还有一个建议，库里面打印错误日志时最好把调用栈也打到日志文件，有时只有一句话都不知道啥错误

**Comment by telanflow** [comment]
好的，有时间我改一下，这个库好像是有问题的（有时候会爆异常导致进程结束），我只是把它用在我司的测试环境，找个时间在优化一波

**Comment by telanflow** [comment]
[Fixed v0.2.4](https://github.com/telanflow/laravel-binlog/releases/tag/0.2.4)
